apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: minio
type: Opaque
data:
  MINIO_ROOT_USER: <base64-encoded-root-user>
  MINIO_ROOT_PASSWORD: <base64-encoded-root-password>

# echo -n 'your-root-user' | base64
# echo -n 'your-root-password' | base64