apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  containers:
  - name: minio
    image: quay.io/minio/minio:latest
    command:
    - /bin/bash
    - -c
    args: 
    - minio server /data --console-address :9001
    env:
    - name: MINIO_ROOT_USER
      valueFrom:
        secretKeyRef:
          name: minio-secrets
          key: MINIO_ROOT_USER
    - name: MINIO_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: minio-secrets
          key: MINIO_ROOT_PASSWORD
    volumeMounts:
    - mountPath: /data
      name: localvolume
  nodeSelector:
    env: minio
  volumes:
  - name: localvolume
    hostPath: 
      path: /home/balu/minio/tmp/data
      type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30000
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 30001
